chore: misc updates and fixes (#1)
* test: use ceph

* test: update container tags

* refactor: swap for our own workflows for chart and container builds while testing

* test: ./

* Revert "test: ./"

This reverts commit a1eef1497a6829c26edb70a4aa431c78237b8614.

* fix: fix dmtcp container

* test: try to fix copy issue

* Revert "test: try to fix copy issue"

This reverts commit 391cf31bd1e7f4486c910c7d5df626abc63c2d61.

* test: build context?

* test: update dmtcp deps

* fix: build context

* fix(dmtcp): update to ubuntu 24.04 from ubuntu 16.04

* fix(rabbit): partially fix container and disable build for now

* chore(deps): bump ubuntu versions in containers

* fix: --break-system-packages

* test: does naively bumping go work

diff --git a/examples/rabbitmq_d/Dockerfile b/examples/rabbitmq_d/Dockerfile
--- a/examples/rabbitmq_d/Dockerfile
+++ b/examples/rabbitmq_d/Dockerfile
@@ -1,15 +1,15 @@
 # The official Canonical Ubuntu Bionic image is ideal from a security perspective,
 # especially for the enterprises that we, the RabbitMQ team, have to deal with
-FROM ubuntu:18.04
+FROM ubuntu:24.04
 
 RUN set -eux; \
 	apt-get update; \
 	apt-get install -y --no-install-recommends \
-# grab gosu for easy step-down from root
+# grab gosu for easy step-down from root\
 		gosu \
 	; \
 	rm -rf /var/lib/apt/lists/*; \
-# verify that the "gosu" binary works
+# verify that the "gosu" binary works\
 	gosu nobody true
 
 
@@ -20,16 +20,15 @@ ARG PGP_KEYSERVER=ha.pool.sks-keyservers.net
 # For context, see https://github.com/docker-library/official-images/issues/4252
 
 # Using the latest OpenSSL LTS release, with support until September 2023 - https://www.openssl.org/source/
-ENV OPENSSL_VERSION 1.1.1d
-ENV OPENSSL_SOURCE_SHA256="1e3a91bc1f9dfce01af26026f856e064eab4c8ee0a8f457b5ae30b40b8b711f2"
+ENV OPENSSL_VERSION 3.5.4
 # https://www.openssl.org/community/omc.html
 ENV OPENSSL_PGP_KEY_IDS="0x8657ABB260F056B1E5190839D9C4D26D0E604491 0x5B2545DAB21995F4088CEFAA36CEE4DEB00CFE33 0xED230BEC4D4F2518B9D7DF41F0DB4D21C1D35231 0xC1F33DD8CE1D4CC613AF14DA9195C48241FBF7DD 0x7953AC1FBC3DC8B3B292393ED5E9E43F7DF9EE8C 0xE5E52560DD91C556DDBDA5D02064C53641C25E5D"
 
 # Use the latest stable Erlang/OTP release (https://github.com/erlang/otp/tags)
-ENV OTP_VERSION 22.1.1
+ENV OTP_VERSION 28.3.1
 # TODO add PGP checking when the feature will be added to Erlang/OTP's build system
 # http://erlang.org/pipermail/erlang-questions/2019-January/097067.html
-ENV OTP_SOURCE_SHA256="9e7e8565a324101ea31fe5f59b8e46f7dabe9b75df9614d24c3abd05885f1773"
+#ENV OTP_SOURCE_SHA256="9e7e8565a324101ea31fe5f59b8e46f7dabe9b75df9614d24c3abd05885f1773"
 
 # Install dependencies required to build Erlang/OTP from source
 # http://erlang.org/doc/installation_guide/INSTALL.html
@@ -50,16 +49,14 @@ RUN set -eux; \
 		libncurses5-dev \
 		make \
 		wget \
-                git \
+        git \
 	; \
 	rm -rf /var/lib/apt/lists/*; \
-	\
-	OPENSSL_SOURCE_URL="https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz"; \
+    OPENSSL_SOURCE_URL="https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz"; \
 	OPENSSL_PATH="/usr/local/src/openssl-$OPENSSL_VERSION"; \
 	OPENSSL_CONFIG_DIR=/usr/local/etc/ssl; \
-	\
-# Required by the crypto & ssl Erlang/OTP applications
-	wget --progress dot:giga --output-document "$OPENSSL_PATH.tar.gz.asc" "$OPENSSL_SOURCE_URL.asc"; \
+# Required by the crypto & ssl Erlang/OTP applications \
+    wget --progress dot:giga --output-document "$OPENSSL_PATH.tar.gz.asc" "$OPENSSL_SOURCE_URL.asc"; \
 	wget --progress dot:giga --output-document "$OPENSSL_PATH.tar.gz" "$OPENSSL_SOURCE_URL"; \
 	export GNUPGHOME="$(mktemp -d)"; \
 	for key in $OPENSSL_PGP_KEY_IDS; do \
@@ -68,55 +65,46 @@ RUN set -eux; \
 	gpg --batch --verify "$OPENSSL_PATH.tar.gz.asc" "$OPENSSL_PATH.tar.gz"; \
 	gpgconf --kill all; \
 	rm -rf "$GNUPGHOME"; \
-	echo "$OPENSSL_SOURCE_SHA256 *$OPENSSL_PATH.tar.gz" | sha256sum --check --strict -; \
 	mkdir -p "$OPENSSL_PATH"; \
 	tar --extract --file "$OPENSSL_PATH.tar.gz" --directory "$OPENSSL_PATH" --strip-components 1; \
-	\
-# Configure OpenSSL for compilation
-	cd "$OPENSSL_PATH"; \
-# without specifying "--libdir", Erlang will fail during "crypto:supports()" looking for a "pthread_atfork" function that doesn't exist (but only on arm32v7/armhf??)
-	debMultiarch="$(dpkg-architecture --query DEB_HOST_MULTIARCH)"; \
-# OpenSSL's "config" script uses a lot of "uname"-based target detection...
-	MACHINE="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)" \
+# Configure OpenSSL for compilation \
+    cd "$OPENSSL_PATH"; \
+# without specifying "--libdir", Erlang will fail during "crypto:supports()" looking for a "pthread_atfork" function that doesn't exist (but only on arm32v7/armhf??) \
+    debMultiarch="$(dpkg-architecture --query DEB_HOST_MULTIARCH)"; \
+    MACHINE="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)" \
 	RELEASE="4.x.y-z" \
 	SYSTEM='Linux' \
 	BUILD='???' \
 	./config \
 		--openssldir="$OPENSSL_CONFIG_DIR" \
 		--libdir="lib/$debMultiarch" \
-# add -rpath to avoid conflicts between our OpenSSL's "libssl.so" and the libssl package by making sure /usr/local/lib is searched first (but only for Erlang/OpenSSL to avoid issues with other tools using libssl; https://github.com/docker-library/rabbitmq/issues/364)
-		-Wl,-rpath=/usr/local/lib \
-	; \
-# Compile, install OpenSSL, verify that the command-line works & development headers are present
-	make -j "$(getconf _NPROCESSORS_ONLN)"; \
+# Compile, install OpenSSL, verify that the command-line works & development headers are present \
+    make -j "$(getconf _NPROCESSORS_ONLN)"; \
 	make install_sw install_ssldirs; \
 	cd ..; \
-	rm -rf "$OPENSSL_PATH"*; \
+	sudo rm -rf "$OPENSSL_PATH"*; \
 	ldconfig; \
-# use Debian's CA certificates
-	rmdir "$OPENSSL_CONFIG_DIR/certs" "$OPENSSL_CONFIG_DIR/private"; \
+    rmdir "$OPENSSL_CONFIG_DIR/certs" "$OPENSSL_CONFIG_DIR/private"; \
 	ln -sf /etc/ssl/certs /etc/ssl/private "$OPENSSL_CONFIG_DIR"; \
-# smoke test
+# smoke test \
 	openssl version; \
 	\
 	OTP_SOURCE_URL="https://github.com/erlang/otp/archive/OTP-$OTP_VERSION.tar.gz"; \
 	OTP_PATH="/usr/local/src/otp-$OTP_VERSION"; \
-	\
-# Download, verify & extract OTP_SOURCE
-	mkdir -p "$OTP_PATH"; \
+# Download, verify & extract OTP_SOURCE \
+    mkdir -p "$OTP_PATH"; \
 	wget --progress dot:giga --output-document "$OTP_PATH.tar.gz" "$OTP_SOURCE_URL"; \
 	echo "$OTP_SOURCE_SHA256 *$OTP_PATH.tar.gz" | sha256sum --check --strict -; \
 	tar --extract --file "$OTP_PATH.tar.gz" --directory "$OTP_PATH" --strip-components 1; \
-	\
-# Configure Erlang/OTP for compilation, disable unused features & applications
-# http://erlang.org/doc/applications.html
-# ERL_TOP is required for Erlang/OTP makefiles to find the absolute path for the installation
-	cd "$OTP_PATH"; \
+# Configure Erlang/OTP for compilation, disable unused features & applications \
+# http://erlang.org/doc/applications.html \
+# ERL_TOP is required for Erlang/OTP makefiles to find the absolute path for the installation \
+    cd "$OTP_PATH"; \
 	export ERL_TOP="$OTP_PATH"; \
 	./otp_build autoconf; \
 	CFLAGS="$(dpkg-buildflags --get CFLAGS)"; export CFLAGS; \
-# add -rpath to avoid conflicts between our OpenSSL's "libssl.so" and the libssl package by making sure /usr/local/lib is searched first (but only for Erlang/OpenSSL to avoid issues with other tools using libssl; https://github.com/docker-library/rabbitmq/issues/364)
-	export CFLAGS="$CFLAGS -Wl,-rpath=/usr/local/lib"; \
+# add -rpath to avoid conflicts between our OpenSSL's "libssl.so" and the libssl package by making sure /usr/local/lib is searched first (but only for Erlang/OpenSSL to avoid issues with other tools using libssl; https://github.com/docker-library/rabbitmq/issues/364) \
+    export CFLAGS="$CFLAGS -Wl,-rpath=/usr/local/lib"; \
 	hostArch="$(dpkg-architecture --query DEB_HOST_GNU_TYPE)"; \
 	buildArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; \
 	dpkgArch="$(dpkg --print-architecture)"; dpkgArch="${dpkgArch##*-}"; \
@@ -154,8 +142,8 @@ RUN set -eux; \
 		--without-tftp \
 		--without-wx \
 	; \
-# Compile & install Erlang/OTP
-	make -j "$(getconf _NPROCESSORS_ONLN)" GEN_OPT_FLGS="-O2 -fno-strict-aliasing"; \
+# Compile & install Erlang/OTP \
+    make -j "$(getconf _NPROCESSORS_ONLN)" GEN_OPT_FLGS="-O2 -fno-strict-aliasing"; \
 	make install; \
 	cd ..; \
 	rm -rf \
@@ -163,9 +151,8 @@ RUN set -eux; \
 		/usr/local/lib/erlang/lib/*/examples \
 		/usr/local/lib/erlang/lib/*/src \
 	; \
-	\
-# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
-	apt-mark auto '.*' > /dev/null; \
+# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies \
+    apt-mark auto '.*' > /dev/null; \
 	[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
 	find /usr/local -type f -executable -exec ldd '{}' ';' \
 		| awk '/=>/ { print $(NF-1) }' \
@@ -175,12 +162,12 @@ RUN set -eux; \
 		| sort -u \
 		| xargs -r apt-mark manual \
 	; \
-	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
-	\
+	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false;
+
 # Check that OpenSSL still works after purging build dependencies
-	openssl version; \
+#RUN openssl version;
 # Check that Erlang/OTP crypto & ssl were compiled against OpenSSL correctly
-	erl -noshell -eval 'io:format("~p~n~n~p~n~n", [crypto:supports(), ssl:versions()]), init:stop().'
+#RUN erl -noshell -eval 'io:format("~p~n~n~p~n~n", [crypto:supports(), ssl:versions()]), init:stop().'
 
 ENV RABBITMQ_DATA_DIR=/var/lib/rabbitmq
 # Create rabbitmq system user & group, fix permissions & allow root user to connect to the RabbitMQ Erlang VM
@@ -196,7 +183,7 @@ RUN set -eux; \
 RUN mkdir ~/.gnupg && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf
 
 # Use the latest stable RabbitMQ release (https://www.rabbitmq.com/download.html)
-ENV RABBITMQ_VERSION 3.8.0-rc.3
+ENV RABBITMQ_VERSION 4.2.2
 # https://www.rabbitmq.com/signatures.html#importing-gpg
 ENV RABBITMQ_PGP_KEY_ID="0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
 ENV RABBITMQ_HOME=/opt/rabbitmq
@@ -217,8 +204,7 @@ RUN set -eux; \
 		xz-utils \
 	; \
 	rm -rf /var/lib/apt/lists/*; \
-	\
-	RABBITMQ_SOURCE_URL="https://github.com/rabbitmq/rabbitmq-server/releases/download/v$RABBITMQ_VERSION/rabbitmq-server-generic-unix-latest-toolchain-$RABBITMQ_VERSION.tar.xz"; \
+    RABBITMQ_SOURCE_URL="https://github.com/rabbitmq/rabbitmq-server/releases/download/v$RABBITMQ_VERSION/rabbitmq-server-generic-unix-latest-toolchain-$RABBITMQ_VERSION.tar.xz"; \
 	RABBITMQ_PATH="/usr/local/src/rabbitmq-$RABBITMQ_VERSION"; \
 	\
 	wget --progress dot:giga --output-document "$RABBITMQ_PATH.tar.xz.asc" "$RABBITMQ_SOURCE_URL.asc"; \
@@ -233,8 +219,8 @@ RUN set -eux; \
 	mkdir -p "$RABBITMQ_HOME"; \
 	tar --extract --file "$RABBITMQ_PATH.tar.xz" --directory "$RABBITMQ_HOME" --strip-components 1; \
 	rm -rf "$RABBITMQ_PATH"*; \
-# Do not default SYS_PREFIX to RABBITMQ_HOME, leave it empty
-	grep -qE '^SYS_PREFIX=\$\{RABBITMQ_HOME\}$' "$RABBITMQ_HOME/sbin/rabbitmq-defaults"; \
+# Do not default SYS_PREFIX to RABBITMQ_HOME, leave it empty \
+    grep -qE '^SYS_PREFIX=\$\{RABBITMQ_HOME\}$' "$RABBITMQ_HOME/sbin/rabbitmq-defaults"; \
 	sed -i 's/^SYS_PREFIX=.*$/SYS_PREFIX=/' "$RABBITMQ_HOME/sbin/rabbitmq-defaults"; \
 	grep -qE '^SYS_PREFIX=$' "$RABBITMQ_HOME/sbin/rabbitmq-defaults"; \
 	chown -R rabbitmq:rabbitmq "$RABBITMQ_HOME"; \
@@ -243,14 +229,16 @@ RUN set -eux; \
 	apt-mark manual $savedAptMark; \
 	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
 	\
-# verify assumption of no stale cookies
+# verify assumption of no stale cookies \
 	[ ! -e "$RABBITMQ_DATA_DIR/.erlang.cookie" ]; \
-# Ensure RabbitMQ was installed correctly by running a few commands that do not depend on a running server, as the rabbitmq user
-# If they all succeed, it's safe to assume that things have been set up correctly
-	gosu rabbitmq rabbitmqctl help; \
+# Ensure RabbitMQ was installed correctly by running a few commands that do not depend on a running server, as the rabbitmq user \
+# If they all succeed, it's safe to assume that things have been set up correctly \
+    set -eux; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends gosu; \
+    gosu rabbitmq rabbitmqctl help; \
 	gosu rabbitmq rabbitmqctl list_ciphers; \
 	gosu rabbitmq rabbitmq-plugins list; \
-# no stale cookies
 	rm "$RABBITMQ_DATA_DIR/.erlang.cookie"
 
 # Added for backwards compatibility - users can simply COPY custom plugins to /plugins
